// apps/web-vue-nuxt/components/ChatInput.vue
<script setup lang="ts">
import { ref, computed } from 'vue'

const props = defineProps<{
  disabled?: boolean
  placeholder?: string
}>()

const emit = defineEmits<{
  send: [content: string]
}>()

const text = ref('')
const isFocused = ref(false)
const textareaRef = ref<HTMLTextAreaElement | null>(null)

const canSend = computed(() => text.value.trim().length > 0 && !props.disabled)

const handleSend = () => {
  if (!canSend.value) return
  emit('send', text.value.trim())
  text.value = ''
  nextTick(() => {
    if (textareaRef.value) {
      textareaRef.value.style.height = 'auto'
    }
  })
}

const handleInput = (e: Event) => {
  const el = e.target as HTMLTextAreaElement
  text.value = el.value
  el.style.height = 'auto'
  el.style.height = `${Math.min(el.scrollHeight, 120)}px`
}

const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  }
}
</script>

<template>
  <div class="px-3 pt-2 pb-2 safe-bottom">
    <div
      class="flex items-end gap-2 bg-white rounded-2xl px-3 py-2 card-shadow transition-all"
      :class="{ 'ring-2 ring-brand-300': isFocused }"
    >
      <textarea
        ref="textareaRef"
        v-model="text"
        class="flex-1 resize-none text-sm leading-6 outline-none bg-transparent max-h-[120px] no-scrollbar placeholder:text-gray-400"
        :placeholder="placeholder || '描述你想要生成的组件...'"
        :disabled="disabled"
        rows="1"
        @focus="isFocused = true"
        @blur="isFocused = false"
        @input="handleInput"
        @keydown="handleKeydown"
      />
      <button
        class="shrink-0 w-10 h-10 rounded-full flex items-center justify-center transition-all disabled:opacity-40 active:scale-95"
        :class="canSend ? 'bg-gradient-primary text-white' : 'bg-gray-200 text-gray-400'"
        :disabled="!canSend"
        @click="handleSend"
      >
        <svg v-if="!disabled" class="w-5 h-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <path d="M22 2L11 13" />
          <path d="M22 2l-7 20-4-9-9-4 20-7z" />
        </svg>
        <svg v-else class="w-5 h-5 animate-spin" viewBox="0 0 24 24" fill="none">
          <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-dasharray="32" />
        </svg>
      </button>
    </div>
    <div class="flex gap-2 mt-2 px-1 overflow-x-auto no-scrollbar">
      <button
        v-for="chip in ['搜索框', '数据表格', '卡片列表', '表单页面', '导航菜单']"
        :key="chip"
        class="shrink-0 chip bg-brand-50 text-brand-600 active:bg-brand-100"
        @click="text = chip + '组件'; textareaRef?.focus()"
      >{{ chip }}</button>
    </div>
  </div>
</template>

// apps/web-react/src/modules/04-chat-ui/ChatInput.tsx
/**
 * 知识点 4.6：移动端输入组件
 *
 * 学习要点：
 * - textarea 自适应高度（scrollHeight 动态设置）
 * - 输入法组合事件（isComposing 判断防止中文输入误触发）
 * - 发送按钮触摸区域（最小 44px）
 *
 * 面试相关：
 * - 如何实现 textarea 自适应高度
 * - compositionstart/compositionend 事件的作用
 */

import { useRef, useCallback } from 'react'
import { Send } from 'lucide-react'

interface ChatInputProps {
  value: string
  isDisabled?: boolean
  onChange: (value: string) => void
  onSend: () => void
}

const MAX_HEIGHT = 120 // textarea 最大高度

const ChatInput: React.FC<ChatInputProps> = ({ value, isDisabled, onChange, onSend }) => {
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // 📝 面试考点：根据 scrollHeight 动态调整 textarea 高度
  const handleInput = useCallback(
    (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      onChange(e.target.value)
      const el = e.target
      // 重置高度后取 scrollHeight，实现自适应
      el.style.height = 'auto'
      el.style.height = `${Math.min(el.scrollHeight, MAX_HEIGHT)}px`
    },
    [onChange],
  )

  // 📝 面试考点：isComposing 判断 — 中文输入法组合状态下不触发发送
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
      if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
        e.preventDefault()
        onSend()
        // 发送后重置高度
        if (textareaRef.current) {
          textareaRef.current.style.height = 'auto'
        }
      }
    },
    [onSend],
  )

  return (
    <div className="flex items-end gap-2 p-3 glass-nav border-t border-slate-700/50">
      <textarea
        ref={textareaRef}
        value={value}
        onChange={handleInput}
        onKeyDown={handleKeyDown}
        placeholder="输入消息..."
        rows={1}
        className="tech-input flex-1 py-2.5 px-3 rounded-xl text-sm resize-none min-h-[40px]"
        style={{ maxHeight: `${MAX_HEIGHT}px` }}
      />
      <button
        type="button"
        onClick={onSend}
        disabled={isDisabled || !value.trim()}
        className="min-w-[44px] min-h-[44px] flex items-center justify-center btn-glow rounded-xl text-white disabled:opacity-30"
      >
        <Send className="w-[18px] h-[18px]" />
      </button>
    </div>
  )
}

export default ChatInput
